name: fireauth
description: A Flutter Package that aims to simplify Flutter Firebase Authentication and streamline development.
version: 0.9.0
homepage: https://github.com/synapsecode/fireauth.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Firebase Dependencies
  firebase_auth_oauth: ^1.1.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  google_sign_in: ^5.2.1
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  flutter_facebook_auth: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: